# Q1: Vectors and matrices

### Focus b: Matrices, matrix operations and their applications
In week 3's exercises we practiced using matrix operations. Matrices are 2D arrays of scalar values, and are central for machine learning. We talk about a matrix' shape or dimensions by its number of rows and number of columns. In this exercise we do matrix multiplication, elementwise multiplication and elementwise difference. 

Matrix operations
1. elementwise difference - subtraction
2. addition can be done the same way, if two matrices are the same size
4. matrix multiplication is a central operation in machine learning. When multiplying two matrices A and B, the output is a new matrix with A-rows and B-columns. Not a symmetric operation, and A's columns must be the same as B's rows. Each element in the output matrix is an inner product of row in A and column in B. 
6. transposing a matrix turns its rows into columns and vice versa. So the first column becomes the first row in the transposed matrix. 
7. matrix inverse. Go to W04, 01-linear_algebra. A square matrix has an inverse if its determinant is not 0, which means that the columns of the matrix span a space. A matrix multiplied with its inverse equals the identity matrix. 

In week 4s exercises, we use the matrix inverse to solve linear systems of equations. 
In week 4s tutorial, we use matrix multiplication to do linear transformations. 

# Linear Algebra

**Overview**
This exercise introduces fundamental linear algebra operations in Numpy and how to use them to solve linear systems of equations. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#diff">Task 1: Elementwise difference</a>
            </li>
            <li>
            <a href="#mul_prop">Task 2: Multiplication properties</a>
            </li>
            <li>
            <a href="#elem_mul">Task 3: Elementwise multiplication - Hadamard pr…</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5],
    [3/2, 0.5],
    [0.25, 1]
])

## Matrix Operations

---
**Task 1 (easy): Elementwise difference👩‍💻**
1. Calculate $A-B$ in the code cell below.


---

In [3]:
# Write your solution here
print(A-B)

[[ 17.         -14.5         14.33333333 -12.75      ]
 [ 12.5        -10.66666667  10.25        -8.8       ]
 [  8.33333333  -6.75         6.2         -4.83333333]
 [  4.25        -2.8          2.16666667  -0.85714286]]



---
**Task 2 (easy): Multiplication properties👩‍💻📽️**
1. Calculate $AC$ and $CA$ in the code cell below. (You may use either [`np.dot`
](https://numpy.org/doc/stable/reference/generated/numpy.dot.html<elem-3>.dot)
 or the `@`
 operator).

2. Explain why the results are different.

3. Calculate $DE$ and $ED$ in the code cell below.

4. Explain what happens and why.



---

In [ ]:
# Write your solution here
print(A@C)
print(C@A)

# 2. the results are different because order matters. 
# AC is rows in A multiplied by columns in C and CA is the opposite. 
# Each scalar in the resulting matrix is the dot product between the row of the first matrix and column of the second matrix

print(D@E)
print(E@D)

# ED is not possible because E's column count should match with D's row count for multipliation to work. 
# E has 2 columns and D has 3 rows. 

[[1.42361111 0.76904762 0.53720238 0.41481481]
 [0.8        0.43968254 0.31071429 0.24166667]
 [0.56666667 0.31380952 0.22301587 0.17407407]
 [0.44126984 0.24540816 0.175      0.13689153]]
[[1.42361111 0.8        0.56666667 0.44126984]
 [0.8        0.46361111 0.33333333 0.26190476]
 [0.50873016 0.29126984 0.20820106 0.16301587]
 [0.39087302 0.22609127 0.16256614 0.12777778]]
[[8.625  3.5   ]
 [2.3125 1.625 ]
 [1.5    2.125 ]]


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)


---
**Task 3 (easy): Elementwise multiplication - Hadamard product👩‍💻**
1. Calculate the elementwise multiplication of $A$ and $C$ using the `*`
 operator.
2. Explain the difference between the `*`
 and `@`
 operators and identify which one is matrix multiplication.


---

In [ ]:
# Write your solution here
print(A*C)

# A*C is elementwise multiplication, where both matrices are the same shape. 
# Each element in A is multiplied with the corresponding element in C. 
# A@C is matrix multiplication, where you find the dot product between rows and columns

[[1.         0.25       0.11111111 0.0625    ]
 [0.25       0.11111111 0.0625     0.04      ]
 [0.11111111 0.05       0.02857143 0.01851852]
 [0.0625     0.02857143 0.02083333 0.01587302]]


---
