# Q2: Exercise week 4 (linear transformations)
### Introduction:
Transformation is changing data within same domain or to another domain. You have some transformation matrix T, input vector x and output vector y. $y = Tx$
For a transformation to be linear, we have some properties that must hold. For vectors u and v, $T(u+v) = T(u) + T(v)$. And scaling the transformation with some constant c, must be the same as scaling the vector with c and then transforming it with T. Visually, we can thnk of a transformation as changing the entire space, like the coordinate system. For the transformation to be linear, the origin must stay in the same place, and lines must remain lines. Nothing should start curving. 
We can think of the columns of T to be basis vectors for this transformed space. In the standard basis, we have basis vectors $[1,0]$ and $[0,1]$. Applying a transformation to a data point is therefore like a linear combination. 

This week's exercises are about using matrix inverses to solve linear systems of equations, and using matrix inverses to estimate model parameters in single variate polynomials. Both exercises uses linear transformations to solve theses problems. 

**Focus a. linear transformations:**

With linear transformations, you can augment the data. We can think of it as changing the underlying coordinate system, not the actual data. 

Show scaling -> x value is scaled by 2, y value is scaled by 3. In higher dimension, add scaling value for each axis. 

Show shearing -> horizontal or vertical

Show rotation -> around origin or around point

3d rotation -> around axis, for higher dimensions 

Remember, for linear transformations, the origin is fixed and all lines stay as lines, as well as staying parallel and evenly spaced. If we want to translate the data, shifting it by some bias, that is not linear, but affine, as we move the origin. To express translations in a single matrix multiplication, we use homogeneous coordinates, which adds another dimension to be able to add this bias. 

There are more non-linear transformations, where the lines curve and so on. 


**Focus b. learning with matrix inverses:**

If we have a dataset, and we want to train a regression model, we need to learn the coefficients. 
For task 5, we solve linear systems of equations using linear algebra. We structure these equations into an inner product $Ax = b$. If we want to isolate x, we can multiply the inverse of A on both sides, such that $x = A^{-1}b$. This works because a matrix multiplied with its own inverse is the identity matrix. Multiplying a vector or matrix with the identity matrix does not change the input. Inverses only exist for square matrices, and the determinant of the matrix must be non-zero. The columns of the matrix must span a space, and not lie in the same direction (the matrix is singular). See for example the last system of equations. 

We do the same when learning model parameters for a polynomial regression model. We form a design matrix, similar to solving the linear equations, containing the input data. Because we also need a bias in our model, we use homogeneous coordinates in our design matrix. Because we need our design matrix to be square, for it to have an inverse, we need a certain amount of data points depending on the complexity of the model. An affine model with the underlying function $y=ax+b$ need 2 points, because we have 2 unknowns. A 2nd order polynomial needs 3 data points and so on. If we had a linear model $y=ax$, then we know that the line hits the origin (0,0). For a 2nd order polynomial with a bias, the rows of the design matrix would be $[x, x^2, 1]$, with 3 columns, and it therefore also needs 3 rows of data points. 

**Focus c. affine transformation, homogeneous coordinates, composition of linear transformation**

Affine transformations are a combination of linear transformation with a translation, meaning that we shift all points in a certain direction. For some linear transformation, we have use some matrix T, where if the data is 2d, then T is 2x2. But how do we do translations with this matrix? How do we move the input based on the origin? We want to add some bias to the data, not scale it. We use homogeneous coordinates for this, which we can also view as projective coordinates. By adding a dimension, we can also shift the data with a bias. 

For a simple translation,
$\begin{bmatrix}1 & 0 & dx \\ 0 & 1 & dy \\ 0 & 0 & 1\end{bmatrix} \begin{bmatrix}x \\ y \\ 1\end{bmatrix}$

If we have several transformations, such as an affine transformation that rotates and translates, we can multiply these matrices to combine them = composition of linear transformation

# Linear Algebra

**Overview**
This exercise is a continuation of week 3 exercise Basic Linear Algebra in Python
. It introduces how to solve linear systems of equations using linear algebra. The goal is to get familiarized with the concepts of linear algebra and how to use them in Numpy.


<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#inverses">Task 1: Inverses</a>
            </li>
            <li>
            <a href="#inverse_prop">Task 2: Inverse properties</a>
            </li>
            <li>
            <a href="#determinant">Task 3: The determinant</a>
            </li>
            <li>
            <a href="#transpose">Task 4: Transpose</a>
            </li>
            <li>
            <a href="#eqsys">Task 5: Solving linear equation systems</a>
            </li>
            <li>
            <a href="#matmul">Task 6: Implementing matrix multiplication</a>
            </li>
            <li>
            <a href="#extra">Task 7: Extra exercises</a>
            </li>
        </ul>
    </div>
</article>

The cell below defines matrices `A`
, `B`
, `C`
, `D`
, `E`
 that are used throughout the exercise:


In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Define matrices to be used in the tasks:
A = np.array([
    [1, 0.5, 1/3, 0.25],
    [0.5, 1/3, 0.25, 0.2],
    [1/3, 0.25, 0.2, 1/6],
    [0.25, 0.2, 1/6, 1/7]
])

B = np.array([
    [-16, 15, -14, 13],
    [-12, 11, -10, 9],
    [-8, 7, -6, 5],
    [-4, 3, -2, 1]
])

C = np.array([
    [1, 1/2, 1/3, 1/4],
    [1/2, 1/3, 1/4, 1/5],
    [1/3, 1/5, 1/7, 1/9],
    [1/4, 1/7, 1/8, 1/9],
])

D = np.array([
    [2, 4, 5/2],
    [-3/4, 2, 0.25],
    [0.25, 0.5, 2]
])

E = np.array([
    [1, -0.5, 3/4],
    [3/2, 0.5, -2],
    [0.25, 1, 0.5]
])

D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)


---
**Task 1 (easy): Inverses👩‍💻**
1. Use [`np.linalg.inv`
](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)
 to calculate  the inverse of $A$ and $C$.
2. Verify that $AA^{-1}=I$ and $CC^{-1}=I$. If the results differ from your expectations, argue why this is the case. 


**Hint**
The question relates to the limitations of floating point numbers.


---

In [ ]:
# Write your solution here
A_inv = np.linalg.inv(A)
C_inv = np.linalg.inv(C)
print(A_inv)
print(C_inv)

print(A@A_inv)
print(C@C_inv)


# I expected the identity matrix as a result, but it does not look correct. 
# The diagonal consists of 1's, but there are not 0's on all spots. 
# it must be because of multiplication of floats 


[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
[[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-1.55431223e-15  1.00000000e+00 -2.38919995e-14 -5.98632255e-14]
 [ 1.11022302e-16 -3.44909286e-14  1.00000000e+00 -8.27486228e-14]
 [-3.45755171e-15  1.10387889e-14 -4.78981933e-14  1.00000000e+00]]
[[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [-6.09734485e-14  1.00000000e+00  3.35864669e-13 -1.96731520e-14]
 [-4.02147451e-15 -8.61903141e-14  1.00000000e+00 -1.43342128e-14]
 [-4.02147451e-15  2.74965236e-14 -1.86591483e-13  1.00000000e+00]]


## Properties

---
**Task 2 (easy): Inverse properties👩‍💻**
Use the code cell below to verify that:
1. $D^{-1}E^{-1} = (ED)^{-1}$
2. $D^{-1}E^{-1} \neq (DE)^{-1}$


---

In [14]:
# Write your solution here
D_inv = np.linalg.inv(D)
E_inv = np.linalg.inv(E)
assert np.allclose(D_inv@E_inv,np.linalg.inv(E@D))
print("1.")
print(D_inv@E_inv)
print(np.linalg.inv(E@D))

assert not np.allclose(D_inv@E_inv,np.linalg.inv(D@E))

print("2.")
print(D_inv@E_inv)
print(np.linalg.inv(D@E))
 

1.
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
2.
[[ 0.25261376  0.13578836 -0.51301587]
 [-0.08601058  0.11462434  0.18539683]
 [ 0.16592593 -0.18962963  0.17777778]]
[[ 0.21096296 -0.256      -0.1517037 ]
 [-0.15365079  0.20571429  0.56634921]
 [ 0.05367196 -0.28342857  0.12833862]]



---
**Task 3 (easy): The determinant👩‍💻**
1. Calculate the determinant of $A$, $B$, and $C$ using [`np.linalg.det`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.det.html<elem-4>.linalg.det)
.
2. Determine which of the matrices $A,B,C$ have an inverse.
3. Calculate the inverses of the matrices using [`np.linalg.inv`
](https://numpy.org/doc/stable/reference/generated/numpy.linalg.inv.html<elem-7>.linalg.inv)
. Explain what happens and how this is related to your answer in (2).


---

In [ ]:
# Write your solution here
print(np.isclose(np.linalg.det(A),0))
print(np.isclose(np.linalg.det(B),0)) 
print(np.isclose(np.linalg.det(C),0))

# A and C both have a determinant that is not 0, so they have an inverse. 
# But B does not have an inverse, because det(B) = 0

print(np.linalg.inv(A))
print(np.linalg.inv(B))
print(np.linalg.inv(C))

# A and C have a unique inverse, like I said earlier. 
# B's inverse is a matrix of very small values?

False
True
False
[[   16.  -120.   240.  -140.]
 [ -120.  1200. -2700.  1680.]
 [  240. -2700.  6480. -4200.]
 [ -140.  1680. -4200.  2800.]]
[[-3.00239975e+16  4.80383960e+16 -6.00479950e+15 -1.20095990e+16]
 [-4.80383960e+16  7.20575940e+16 -0.00000000e+00 -2.40191980e+16]
 [-6.00479950e+15  0.00000000e+00  1.80143985e+16 -1.20095990e+16]
 [ 1.20095990e+16 -2.40191980e+16  1.20095990e+16 -0.00000000e+00]]
[[   -72.   -225.    525.     42.]
 [  1260.   3675.  -8820.   -630.]
 [ -3696. -10710.  25830.   1764.]
 [  2700.   7830. -18900.  -1260.]]



---
**Task 4 (easy): Transpose👩‍💻**
1. Verify that $(D^{-1})^\top$ and ${D^\top}^{-1}$ are equal.


**Hint**
The transpose of a matrix `A`
 in Numpy can be calculated with `A.T`
.


---

In [17]:
# Write your solution here
assert np.allclose(D_inv.T, np.linalg.inv(D.T))

## Linear equations
Matrices can represent systems of linear equations

$$
Ax=b
$$
where $A$ is the coefficient matrix, $x$ the vector of unknowns, and $b$ is the vector of the dependent variables.
A solution can be found using

$$
\begin{align*}
A^{-1}Ax&=A^{-1}b\\
x &= A^{-1}b.
\end{align*}
$$

---
**Task 5 (medium): Solving linear equation systems👩‍💻**
For each of the following sets of linear equations determine whether a unique solution exits. Recall that the determinant 
can be used to determine whether a matrix has an inverse. Your answers have to be submitted in [Grasple](https://app.grasple.com/#/courses/10532/ci/733997/diagnoses/12886)
:
a)

$$ 
\begin{align*}
2x + 3y  &= -1\\
x + y  &= 0\\
\end{align*}
$$
b)

$$
\begin{align*}
1x + 0y  &= 5\\
0x + 1y  &= 7\\
\end{align*}
$$
c)

$$
\begin{align*}
0x + y  &= -1\\
-2x + -3y  &= 2\\
\end{align*}
$$
d)

$$
\begin{align*}
x + -3y + 3z &= 0.5\\
x - 5y + 3z& = 0.5\\
6z + -6y + 4x &= 1.
\end{align*}
$$
e)

$$
\begin{align*}
2x + 3y + 4z &= 2\\
x + 4z + y &= -2\\
4z + 5y + 2x &= 3.
\end{align*}
$$
f)

$$
\begin{align*}
x + y + z &= 2\\
2x + 2z + 2y &= -2\\
3z + 3y + 3x &= 3.
\end{align*}
$$

---

In [ ]:
# Write your solutions here

# A
a_A = np.array([
    [2, 3], [1, 1]
])
print(np.linalg.det(a_A))
assert not np.isclose(np.linalg.det(a_A), 0)
# yes it has a unique solution
print(np.linalg.inv(a_A)@np.array([[-1],[0]]))


# B
b_A = np.array([
    [1, 0], [0, 1]
])
print(np.linalg.det(b_A))
assert not np.isclose(np.linalg.det(b_A),0)
# yes it has a unique solution
print(np.linalg.inv(b_A)@np.array([[5],[7]]))


# C
c_A = np.array([
    [0, 1], [-2, -3]
])
print(np.linalg.det(c_A))
assert not np.isclose(np.linalg.det(c_A),0)
# yes it has a unique solution
print(np.linalg.inv(c_A)@np.array([[-1],[2]]))



# D
d_A = np.array([
    [1, -3, 3], [1, -5, 3], [4, -6, 6]
])
print(np.linalg.det(d_A))
assert not np.isclose(np.linalg.det(d_A),0)
# yes it has a unique solution
print(np.linalg.inv(d_A)@np.array([[0.5], [0.5], [1]]))


# E
e_A = np.array([
    [2, 3, 4], [1, 1, 4], [2, 5, 4]
])
print(np.linalg.det(e_A))
assert not np.isclose(np.linalg.det(e_A),0)
# yes it has a unique solution
print(np.linalg.inv(e_A)@np.array([[2], [-2], [3]]))


# F
f_A = np.array([
    [1, 1, 1], [2, 2, 2], [3, 3, 3]
])
print(np.linalg.det(f_A))
assert np.isclose(np.linalg.det(f_A),0)
# no it does not a unique solution


-1.0
[[ 1.]
 [-1.]]
1.0
[[5.]
 [7.]]
2.0
[[ 0.5]
 [-1. ]]
12.000000000000005
[[-5.55111512e-17]
 [ 1.58603289e-17]
 [ 1.66666667e-01]]
-7.999999999999998
[[ 3.   ]
 [ 0.5  ]
 [-1.375]]
-1.8488927466117412e-32


## Matrix multiplication (optional)
For an $N\times D$ matrix $A$ and a $D\times K$ matrix $B$, the 
matrix multiplication (or matrix product) is an $N\times K$ matrix $R$. Elements $R_{ij}$ of $R$ can be calculated 
using the following formula

$$
R_{ij} = \sum_{d=1}^D A_{id}B_{dj}.
$$
In other words, it is the dot product of the $i$'th row vector of $A$ and the $j$'th column vector of $B$.

---
**Task 6 (medium): Implementing matrix multiplication👩‍💻**
Implement matrix multiplication in the `matmul`
 function in the code cell below. You may use either Python lists or Numpy arrays, but the intention is to not use Numpy's functions for matrix multiplication (i.e., `np.dot`
, `@`
, `np.matmul`
, etc.). You may, however, use `np.dot`
 for the purpose of computing the inner product between row and column vectors.

**Hint**
It might be helpful to calculate the correct result by hand first, to make debugging easier.


---

In [0]:
def matmul(a, b):
    # Implement this function
    ...
    

ma = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

mb = [
    [5, 4, 9],
    [2, 1, 7],
    [8, 0, 1]
]

matmul(ma, mb)


---
**Task 7 (easy): Extra exercises💡**
Additional exercises are available on Grasple. Complete these if you need more practice with fundamental linear algebra operations and properties:
1. [Matrix Operations](https://app.grasple.com/#/courses/10532/ci/694300/subjects/3936)

2. [Addition, Scalar Multiplication and Transposition](https://app.grasple.com/#/courses/10532/ci/694301/subjects/3935)

3. [Inverse Matrices](https://app.grasple.com/#/courses/10532/ci/735682/subjects/3939)



---