# Q10

### Focus a: basis and transformations
We can view any vector in the standard basis as a linear combination of the basis vectors and the vector values as scalars. The standard basis matrix is the same as the identity matrix for that dimension. 
We can represent any basis with a set of linear independent vectors. Linear independence = cannot create one from linear combination of the others. Linear independent vectors will span a space. Point in different directions. 
First task, we're asked if two vectors form a basis in 2d (subspace). Last vectors are linearly dependent, point in same direction. 

Task 2, asked to transform vector from standard basis to other. Use inverse of destination basis matrix to transform. Use current basis matrix to change back to standard. Linear transformation.

Task 3, how to describe transformation matrix in basis B? Change basis to standard, apply transformation, change basis to B. 

When doing PCA, we change basis from the standard basis, to a smaller K dimension with the most important K eigenvectors as basis vectors. 

# Bases and transformations
The following tasks are designed to provide a refresher on bases and transformations between them.

<article class="message">
    <div class="message-body">
        <strong>List of individual tasks</strong>
        <ul style="list-style: none;">
            <li>
            <a href="#basis">Task 1: Identifying Basis Vectors</a>
            </li>
            <li>
            <a href="#basis_combined">Task 2: Basis Transformation and Change of Coord…</a>
            </li>
            <li>
            <a href="#basis4">Task 3: Applying a Linear Transformation in Diff…</a>
            </li>
            <li>
            <a href="#basis5">Task 4: Basis and Dimensionality Check</a>
            </li>
        </ul>
    </div>
</article>


---
**Task 1 (easy): Identifying Basis Vectors♾️**
Given the following bases vectors for $\mathbb{R}^2$:

$$
\begin{array}{l}
1. \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\} \\[12pt]
2. \left\{ \begin{bmatrix} 2 \\ 3 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\} \\[12pt]
3. \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 2 \\ 2 \end{bmatrix} \right\} \\
\end{array}
$$
1. Which of these sets forms a basis for $\mathbb{R}^2 $? Justify your answer by checking linear independence and spanning the vector space.


---

In [5]:
# Write solutions here
import numpy as np

# 1. forms a basis for R2, as they are linear independent, and we can form any 2d vector from linear combination. 
# linear independence = only way to get zero vector by linear combination is having all scalars to be 0. 
m_1 = np.array([[1,0],[0,1]]).T
print(np.linalg.matrix_rank(m_1) == 2)

# 2. yes
m_2 = np.array([[2,3],[-1,2]]).T
print(np.linalg.matrix_rank(m_2) == 2)

#3. no
m_3 = np.array([[1,1],[2,2]]).T
print(np.linalg.matrix_rank(m_3) == 2)


True
True
False



---
**Task 2 (hard): Basis Transformation and Change of Coordinates♾️**
Consider three bases in  $\mathbb{R}^2$:
1. The standard basis  
$$E = \left\{ \begin{bmatrix} 1 \\ 0 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \end{bmatrix} \right\}$$
 
2. The basis  
$$B   = \left\{ \begin{bmatrix} 1 \\ 2 \end{bmatrix}, \begin{bmatrix} 2 \\ -1 \end{bmatrix} \right\}$$
 
3. The basis  
$$C   = \left\{ \begin{bmatrix} 2 \\ 1 \end{bmatrix}, \begin{bmatrix} 1 \\ 3 \end{bmatrix} \right\}$$
 

Given two vectors in the standard basis:

$$
\text{v} = \begin{bmatrix} 3 \\ 1 \end{bmatrix}, 
\text{w} = \begin{bmatrix} 7 \\ 6 \end{bmatrix} 
$$
1. Draw the basis vectors for  $E$,  $B$ , and  $C$ and the vectors $\text{v}$ and $\text{w}$  on a piece of paper.

2. Express $\text{v}$ and $\text{w}$  in the basis  $B$. 

3. Express $\text{v}$  and $\text{w}$  in the basis $C$.

4. Find the change of basis matrix  $T_E^B$ that given a vector expressed in the basis  E  maps it to the basis B. 

5. Find the change of basis matrix  $T_E^C$ that given a vector expressed in the basis  E  maps it to the basis C.

6. Use the change of basis matrices to transform  $\text{v}$ and $\text{w}$ from standard basis to the basis $B$ and $C$ respectively. Verify that the resulting coordinates match your results from the previous steps.



---

In [12]:
# Write solutions here

B = np.array([[1,2], [2,-1]]).T
C = np.array([[2,1],[1,3]]).T
v = np.array([3,1]).T
w = np.array([7,6]).T

print("change of basis matrix from E to B:\n", np.linalg.inv(B))

v_B = np.linalg.inv(B)@v
print("\nv_B:", v_B)

w_B = np.linalg.inv(B)@w
print("\nw_B:", w_B)

print("\nchange of basis matrix from E to C: \n", np.linalg.inv(C))


print("\nv_C:", np.linalg.inv(C)@v) 
print("\nw_C:", np.linalg.inv(C)@w) 

change of basis matrix from E to B:
 [[ 0.2  0.4]
 [ 0.4 -0.2]]

v_B: [1. 1.]

w_B: [3.8 1.6]

change of basis matrix from E to C: 
 [[ 0.6 -0.2]
 [-0.2  0.4]]

v_C: [ 1.6 -0.2]

w_C: [3. 1.]



---
**Task 3 (easy): Applying a Linear Transformation in Different Bases♾️**
Let $ T: \mathbb{R}^2 \to \mathbb{R}^2 $ be a linear transformation represented by the matrix:

$$
A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$$

in the standard basis. Let 

$$
B = \left\{ \begin{bmatrix} 1 \\ 1 \end{bmatrix}, \begin{bmatrix} -1 \\ 2 \end{bmatrix} \right\}
$$
 
be a new basis.
1. Calculate the matrix that represents $ T $ with respect to the basis $ B $. Use the change of basis matrices to show your work.


---

$$A_B = B^{-1}AB$$
1. to standard basis
2. transform using A
3. back to basis B

In [15]:
# Write solutions here
A = np.array([[1,3],[2,4]]).T
B = np.array([[1,1],[-1,2]])

print("change of basis matrix from standard basis to B: \n", np.linalg.inv(B))

print("\nchange of basis matrix from B to standard basis\n", B)

print("\nA in basis B:\n", np.linalg.inv(B)@A@B)

change of basis matrix from standard basis to B: 
 [[ 0.66666667 -0.33333333]
 [ 0.33333333  0.33333333]]

change of basis matrix from B to standard basis
 [[ 1  1]
 [-1  2]]

A in basis B:
 [[-0.33333333 -0.33333333]
 [-0.66666667  5.33333333]]



---
**Task 4 (easy): Basis and Dimensionality Check♾️**
Suppose $ \mathbb{R}^3 $ has a basis given by 

$$
B = \left\{ \begin{bmatrix} 1 \\ 0 \\ 1 \end{bmatrix}, \begin{bmatrix} 0 \\ 1 \\ 1 \end{bmatrix}, \begin{bmatrix} 0 \\ 0 \\ 1 \end{bmatrix} \right\}.
$$

1. Verify that $ B $ is a basis by showing it spans $ \mathbb{R}^3 $ and is linearly independent.
2. If a fourth vector $ \begin{bmatrix} 2 \\ -1 \\ 3 \end{bmatrix} $ is added to $ B $, does it still form a basis for $ \mathbb{R}^3 $? Explain your reasoning in terms of dimension.


---

In [ ]:
# Write solutions here

B = np.array([[1,0,1],[0,1,1],[0,0,1]]).T
print("rank of B is", np.linalg.matrix_rank(B))

# fourth vector is redundant for basis for 3d subspace. 3 linearly independent 3d vectors to form basis in 3d 

rank of B is 3
